
services:
  nginx:
    image: nicolassarmiento8/dou-gateway:latest
    ports:
      - "8080:80" 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  
    depends_on:
      - auth_service
      - users_service
      - submission_service
      - problem_service
      - material_service
    networks:
      - dou_network
  auth_service:
    image: nicolassarmiento8/dou-auth:latest
    ports:
      - "8000" 
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - dou_network
  
  users_service:
    image: nicolassarmiento8/dou-users:latest
    ports:
      - "8000" 
    depends_on:
      - db
      - auth_service
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - dou_network

  problem_service:
    image: nicolassarmiento8/dou-problem:latest
    ports:
      - "8000" 
    depends_on:
      - db
      - auth_service
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - problem_storage:/app/problems
    networks:
      - dou_network

  submission_service:
    image: nicolassarmiento8/dou-submission:latest
    ports:
      - "8000" 
    depends_on:
      - db
      - auth_service
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JUDGE_IP=${JUDGE_IP}
    volumes:
      - problem_storage:/app/problems 
      - submission_storage:/app/submissions
    networks:
      - dou_network
 
  material_service:
    image: nicolassarmiento8/dou-material:latest
    ports:
      - "8000" 
    depends_on:
      - db
      - auth_service
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - material_storage:/app/materials
    networks:
      - dou_network

  frontend:
    image: joseslk/dou-frontend:latest
    ports:
      - "5173:5173"
    networks:
      - dou_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped


  db:
    image: nicolassarmiento8/dou-db:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dou_network
    
volumes:
  postgres_data:
  problem_storage:
  submission_storage:
  material_storage:

networks:
  dou_network: {}