
services:
  auth_service:
    build: 
      context: ./services/auth_service
    container_name: dou_code_auth_service
    image: dou-code-auth_service
    ports:
      - "8000:8000" 
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - dou_network
  
  users_service:
    build: 
      context: ./services/users_service
    container_name: dou_code_users_service
    image: dou-code-users_service
    ports:
      - "8001:8000" 
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - dou_network

  db:
    build: 
      context: ./db
    container_name: dou_code_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dou_network
    
volumes:
  postgres_data:

networks:
  dou_network: {}