
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80" 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  
    depends_on:
      - auth_service
      - users_service
      - submission_service
      - problem_service
    networks:
      - dou_network
  auth_service:
    build: 
      context: ./services/auth_service
    container_name: dou_code_auth_service
    image: dou-code-auth-service
    ports:
      - "8000" 
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - dou_network
  
  users_service:
    build: 
      context: ./services/users_service
    container_name: dou_code_users_service
    image: dou-code-users-service
    ports:
      - "8000" 
    depends_on:
      - db
      - auth_service
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - dou_network

  problem_service:
    build: 
      context: ./services/problem_service
    container_name: dou_code_problem_service
    image: dou-code-problem-service
    ports:
      - "8000" 
    depends_on:
      - db
      - auth_service
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - problem_storage:/app/problems
    networks:
      - dou_network

  submission_service:
    build: 
      context: ./services/submission_service
    container_name: dou_code_submission_service
    image: dou-code-submission-service
    ports:
      - "8080" 
    depends_on:
      - db
      - auth_service
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JUDGE_URL=${JUDGE_URL}
    volumes:
      - problem_storage:/app/problems 
      - submission_storage:/app/submissions
      
    networks:
      - dou_network

  db:
    build: 
      context: ./db
    container_name: dou_code_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dou_network
    
volumes:
  postgres_data:
  problem_storage:
  submission_storage:

networks:
  dou_network: {}