
services:
  auth_service:
    build: 
      context: ./services/auth_service
    container_name: dou_code_auth_service
    image: dou-code-auth_service
    ports:
      - "8000:8000" 
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://dou_code_dba:Ahri34@@db:5432/dou_code
  
  users_service:
    build: 
      context: ./services/users_service
    container_name: dou_code_users_service
    image: dou-code-users_service
    ports:
      - "8001:8000" 
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://dou_code_dba:Ahri34@@db:5432/dou_code

  db:
    build: 
      context: ./db
    container_name: dou_code_db
    environment:
      POSTGRES_USER: dou_code_dba
      POSTGRES_PASSWORD: Ahri34@
      POSTGRES_DB: dou_code
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
volumes:
  postgres_data:
